spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/spring-learning-newbie
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  sql:
    init:
      schema-locations: classpath*:schema.sql
      mode: always